import SwiftUI

/// Lets the user optionally configure a Claude API key so lyric generation uses
/// `ClaudeLyricGenerationService` instead of the built-in local generator. The key
/// is stored in the Keychain, never in UserDefaults or the SwiftData store.
struct LyricServiceSettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var apiKey: String = KeychainService.loadAPIKey() ?? ""

    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background.ignoresSafeArea()

                VStack(alignment: .leading, spacing: AppTheme.Spacing.lg) {
                    VStack(alignment: .leading, spacing: AppTheme.Spacing.sm) {
                        Text("Claude API Key")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(AppTheme.textSecondary)
                            .textCase(.uppercase)

                        SecureField("sk-ant-...", text: $apiKey)
                            .textContentType(.password)
                            .autocorrectionDisabled()
                            .padding(AppTheme.Spacing.md)
                            .background(AppTheme.surface)
                            .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.sm, style: .continuous))
                            .foregroundStyle(AppTheme.textPrimary)

                        Text("Optional. Without a key, lyrics are written by the built-in local generator — fully offline, no account needed. With a key, lyrics are generated by Claude for higher quality, more varied results.")
                            .font(.footnote)
                            .foregroundStyle(AppTheme.textTertiary)
                    }

                    Spacer()

                    Button(role: .destructive) {
                        apiKey = ""
                        KeychainService.saveAPIKey("")
                    } label: {
                        Text("Clear Key")
                            .font(.headline)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                    }
                    .foregroundStyle(AppTheme.danger)
                    .background(AppTheme.surface)
                    .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.pill, style: .continuous))

                    Button {
                        KeychainService.saveAPIKey(apiKey)
                        dismiss()
                    } label: {
                        Text("Save")
                            .font(.headline)
                            .foregroundStyle(.black)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                    }
                    .background(Color.white)
                    .clipShape(RoundedRectangle(cornerRadius: AppTheme.Radius.pill, style: .continuous))
                }
                .padding(AppTheme.Spacing.lg)
            }
            .navigationTitle("Lyric Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
    }
}
